language: ruby
rvm:
  - 2.2

branches:
  only:
    - master

addons:
  postgresql: "9.4"

env:
  - REDMINE_VER=3.1-stable
#  - REDMINE_VER=master

install: "echo skip bundle install"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create extension unaccent;' -U postgres travis_ci_test

script:
  - export RAILS_ENV=test
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_postgresql_search
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - export PATH_TO_TESTER=`pwd`/redmine_tester.sh
  - mkdir $TESTSPACE
  - cp test/support/* $TESTSPACE/
  - bash -x ./redmine_install.sh -c
  - bash -x ./redmine_install.sh -i
  - bash -x ./redmine_install.sh -t
