name: Tests
on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.redmine }} ${{ matrix.db }} ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.6', '2.4']
        redmine: ['4.1-stable', 'master']
        db: ['postgres12', 'postgres13']
      fail-fast: false

    services:
      postgres12:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres13:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5433

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Redmine
        uses: actions/checkout@v2
        with:
          repository: redmine/redmine
          ref: ${{ matrix.redmine }}
          path: redmine

      - name: Checkout additionals
        uses: actions/checkout@v2
        with:
          repository: AlphaNodes/additionals
          path: redmine/plugins/additionals

      - name: Checkout redmine_postgresql_search
        uses: actions/checkout@v2
        with:
          path: redmine/plugins/redmine_postgresql_search

      - name: Update package archives
        run: sudo apt-get update --yes --quiet

      - name: Install package dependencies
        run: >
          sudo apt-get install --yes --quiet
          build-essential
          cmake
          libicu-dev
          libpq-dev

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: v1-ruby-${{ matrix.ruby }}-redmine-${{ matrix.redmine }}

      - name: Setup Bundler
        run: |
          gem install bundler -v '~> 1.0'
          bundle config path "$(pwd)/vendor/bundle"

      - name: Prepare Redmine source
        working-directory: redmine
        run: |
          cp plugins/redmine_postgresql_search/test/support/database-${{ matrix.db }}.yml config/database.yml
          cp plugins/redmine_postgresql_search/test/support/configuration.yml config/configuration.yml

      - name: Install Ruby dependencies
        working-directory: redmine
        run: |
          bundle install --jobs=4 --retry=3 --without development

      - name: Run Redmine rake tasks
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: |
          bundle exec rake generate_secret_token
          bundle exec rake db:create db:migrate redmine:plugins:migrate
          bundle exec rake db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
          REDMINE_VERSION: ${{ matrix.redmine }}
        working-directory: redmine
        run: bundle exec rake redmine:plugins:test NAME=redmine_postgresql_search RUBYOPT="-W0"

      - name: Run rebuild index
        env:
          RAILS_ENV: test
          REDMINE_VERSION: ${{ matrix.redmine }}
        working-directory: redmine
        run: bundle exec rake redmine_postgresql_search:rebuild_index

      - name: Run uninstall test
        env:
          RAILS_ENV: test
          REDMINE_VERSION: ${{ matrix.redmine }}
        working-directory: redmine
        run: bundle exec rake redmine:plugins:migrate NAME=redmine_postgresql_search VERSION=0
